# Generated by Django 4.0.5 on 2022-06-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_neighbourhood_post_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
